export let ProductSpecsLaptop: {
  id?: string;              // Auto-Generated by MongoDB
  product_id: string;       // ID of corresponding product

  cpu_spec: string;
  gpu_spec: string;
  ram_spec: string;
  screen_spec: string;
  battery_spec: string;
}
