export type User = {
  id?: string; // Generated by MongoDB

  user_email: string;
  user_password: string; // This will be stored in db as hash values

  // I've always hated when you HAVE to give your real name
  // user_profile_info?: {
  //   first_name?: string;
  //   last_name?: string;
  //   age?: number;
  //   telefon?: string;
  //   gender?: "M" | "F";
  // };

};
