export const products = [
  {
    id: '000000000001',
    name: 'Laptop',
    img: '',
    price: '500',
    rating: '',
    comments: '',
    specs: '',
    seller: '',
    sold: 0,
  },
  {
    id: '000000000002',
    name: 'Desktop',
    img: '',
    price: '300',
    rating: '',
    comments: '',
    specs: '',
    seller: '',
    sold: 0,
  },
  {
    id: '000000000003',
    name: 'Laptop #2',
    img: '',
    price: '750',
    rating: '',
    comments: '',
    specs: '',
    seller: '',
    sold: 0,
  },
  {
    id: '000000000004',
    name: 'Mechanical Keyboard',
    img: '',
    price: '150',
    rating: '',
    comments: '',
    specs: '',
    seller: '',
    sold: 0,
  },
  {
    id: '000000000005',
    name: 'Mouse',
    img: '',
    price: '100',
    rating: '',
    comments: '',
    specs: '',
    seller: '',
    sold: 0,
  },
  {
    id: '000000000006',
    name: 'Speakers',
    img: '',
    price: '200',
    rating: '',
    comments: '',
    specs: '',
    seller: '',
    sold: 0,
  },
  {
    id: '000000000007',
    name: 'Monitor',
    img: '',
    price: '350',
    rating: '',
    comments: '',
    specs: '',
    seller: '',
    sold: 0,
  },
  {
    id: '000000000008',
    name: 'HDMI Cable',
    img: '',
    price: '15',
    rating: '',
    comments: '',
    specs: '',
    seller: '',
    sold: 0,
  },
];
